name: AInv2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.0.0
  - pytorch-cuda=11.8  # Adjust based on your CUDA version (11.8 or 12.1)
  - faiss-gpu  # Use faiss-cpu if no GPU available
  - numpy>=1.24.0
  - pip
  - pip:
    - fastapi>=0.110.0
    - uvicorn[standard]>=0.29.0
    - python-dotenv>=1.0.0
    - pydantic>=2.6.0
    - openai>=1.0.0
    - pydantic-ai>=0.2.0
    - groq
    - sentence-transformers>=2.2.0
    - httpx>=0.24.0
    - aiohttp>=3.8.0
    - jinja2>=3.1.0
    - python-multipart>=0.0.9
    - logfire
    - opentelemetry-instrumentation-asyncpg
    - debugpy
    - typing-extensions>=4.5.0 