ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG TAG
ARG COMPILED_REQUIREMENTS_FILE

RUN yum update -y
RUN yum upgrade -y

RUN yum install python39 -y
RUN python3 -m ensurepip --upgrade
RUN pip3 install -U pip setuptools wheel pip-tools

RUN mkdir /temp

COPY ./requirements_files/${COMPILED_REQUIREMENTS_FILE} /temp/${COMPILED_REQUIREMENTS_FILE}
RUN cat /temp/${COMPILED_REQUIREMENTS_FILE}
RUN python3 -m piptools compile /temp/${COMPILED_REQUIREMENTS_FILE} --resolver=backtracking