version: '3.8'

services:
  raw-logger-proxy:
    build: .
    container_name: raw-logger-proxy
    ports:
      - "4001:4001"
    environment:
      - LITELLM_HOST=litellm
      - LITELLM_PORT=4000
      - PROXY_PORT=4001
      - LOG_DIR=/app/logs
      - MAX_BODY_LOG_SIZE=10485760  # 10MB
      - LOG_FORMAT=json
    volumes:
      - ./logs:/app/logs
    networks:
      - litellm_network
    depends_on:
      - litellm
    restart: unless-stopped

networks:
  litellm_network:
    driver: bridge