[install]
is_configured = 1
build = 1

[ui]
is_visible = 1
label = DSDL Examples

[launcher]
author = Splunk Inc.
description = Companion example dashboards for Splunk App for Data Science and Deep Learning
version = 5.2.3

[package]
id = dsdl-examples

[id]
name = dsdl-examples
version = 5.2.3
